(cl:defpackage diagnostic_msgs-srv
  (:use )
  (:export
   "SELFTEST"
   "<SELFTEST-REQUEST>"
   "SELFTEST-REQUEST"
   "<SELFTEST-RESPONSE>"
   "SELFTEST-RESPONSE"
   "ADDDIAGNOSTICS"
   "<ADDDIAGNOSTICS-REQUEST>"
   "ADDDIAGNOSTICS-REQUEST"
   "<ADDDIAGNOSTICS-RESPONSE>"
   "ADDDIAGNOSTICS-RESPONSE"
  ))

