(cl:defpackage smach_msgs-msg
  (:use )
  (:export
   "<SMACHCONTAINERSTATUS>"
   "SMACHCONTAINERSTATUS"
   "<SMACHCONTAINERSTRUCTURE>"
   "SMACHCONTAINERSTRUCTURE"
   "<SMACHCONTAINERINITIALSTATUSCMD>"
   "SMACHCONTAINERINITIALSTATUSCMD"
  ))

