; Auto-generated. Do not edit!


(cl:in-package actionlib-msg)


;//! \htmlinclude TestRequestFeedback.msg.html

(cl:defclass <TestRequestFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TestRequestFeedback (<TestRequestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestRequestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestRequestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib-msg:<TestRequestFeedback> is deprecated: use actionlib-msg:TestRequestFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestRequestFeedback>) ostream)
  "Serializes a message object of type '<TestRequestFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestRequestFeedback>) istream)
  "Deserializes a message object of type '<TestRequestFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestRequestFeedback>)))
  "Returns string type for a message object of type '<TestRequestFeedback>"
  "actionlib/TestRequestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestRequestFeedback)))
  "Returns string type for a message object of type 'TestRequestFeedback"
  "actionlib/TestRequestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestRequestFeedback>)))
  "Returns md5sum for a message object of type '<TestRequestFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestRequestFeedback)))
  "Returns md5sum for a message object of type 'TestRequestFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestRequestFeedback>)))
  "Returns full string definition for message of type '<TestRequestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestRequestFeedback)))
  "Returns full string definition for message of type 'TestRequestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestRequestFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestRequestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TestRequestFeedback
))
