; Auto-generated. Do not edit!


(cl:in-package actionlib-msg)


;//! \htmlinclude TestGoal.msg.html

(cl:defclass <TestGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:integer
    :initform 0))
)

(cl:defclass TestGoal (<TestGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib-msg:<TestGoal> is deprecated: use actionlib-msg:TestGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <TestGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib-msg:goal-val is deprecated.  Use actionlib-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestGoal>) ostream)
  "Serializes a message object of type '<TestGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestGoal>) istream)
  "Deserializes a message object of type '<TestGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestGoal>)))
  "Returns string type for a message object of type '<TestGoal>"
  "actionlib/TestGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestGoal)))
  "Returns string type for a message object of type 'TestGoal"
  "actionlib/TestGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestGoal>)))
  "Returns md5sum for a message object of type '<TestGoal>"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestGoal)))
  "Returns md5sum for a message object of type 'TestGoal"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestGoal>)))
  "Returns full string definition for message of type '<TestGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestGoal)))
  "Returns full string definition for message of type 'TestGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TestGoal
    (cl:cons ':goal (goal msg))
))
