; Auto-generated. Do not edit!


(cl:in-package actionlib-msg)


;//! \htmlinclude TwoIntsFeedback.msg.html

(cl:defclass <TwoIntsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TwoIntsFeedback (<TwoIntsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TwoIntsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TwoIntsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib-msg:<TwoIntsFeedback> is deprecated: use actionlib-msg:TwoIntsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TwoIntsFeedback>) ostream)
  "Serializes a message object of type '<TwoIntsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TwoIntsFeedback>) istream)
  "Deserializes a message object of type '<TwoIntsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TwoIntsFeedback>)))
  "Returns string type for a message object of type '<TwoIntsFeedback>"
  "actionlib/TwoIntsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TwoIntsFeedback)))
  "Returns string type for a message object of type 'TwoIntsFeedback"
  "actionlib/TwoIntsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TwoIntsFeedback>)))
  "Returns md5sum for a message object of type '<TwoIntsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TwoIntsFeedback)))
  "Returns md5sum for a message object of type 'TwoIntsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TwoIntsFeedback>)))
  "Returns full string definition for message of type '<TwoIntsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TwoIntsFeedback)))
  "Returns full string definition for message of type 'TwoIntsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TwoIntsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TwoIntsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TwoIntsFeedback
))
