; Auto-generated. Do not edit!


(cl:in-package control_msgs-msg)


;//! \htmlinclude JointTrajectoryResult.msg.html

(cl:defclass <JointTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JointTrajectoryResult (<JointTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_msgs-msg:<JointTrajectoryResult> is deprecated: use control_msgs-msg:JointTrajectoryResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointTrajectoryResult>) ostream)
  "Serializes a message object of type '<JointTrajectoryResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointTrajectoryResult>) istream)
  "Deserializes a message object of type '<JointTrajectoryResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointTrajectoryResult>)))
  "Returns string type for a message object of type '<JointTrajectoryResult>"
  "control_msgs/JointTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointTrajectoryResult)))
  "Returns string type for a message object of type 'JointTrajectoryResult"
  "control_msgs/JointTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointTrajectoryResult>)))
  "Returns md5sum for a message object of type '<JointTrajectoryResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointTrajectoryResult)))
  "Returns md5sum for a message object of type 'JointTrajectoryResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointTrajectoryResult>)))
  "Returns full string definition for message of type '<JointTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointTrajectoryResult)))
  "Returns full string definition for message of type 'JointTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointTrajectoryResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointTrajectoryResult
))
