; Auto-generated. Do not edit!


(cl:in-package control_msgs-msg)


;//! \htmlinclude PointHeadFeedback.msg.html

(cl:defclass <PointHeadFeedback> (roslisp-msg-protocol:ros-message)
  ((pointing_angle_error
    :reader pointing_angle_error
    :initarg :pointing_angle_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass PointHeadFeedback (<PointHeadFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointHeadFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointHeadFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_msgs-msg:<PointHeadFeedback> is deprecated: use control_msgs-msg:PointHeadFeedback instead.")))

(cl:ensure-generic-function 'pointing_angle_error-val :lambda-list '(m))
(cl:defmethod pointing_angle_error-val ((m <PointHeadFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader control_msgs-msg:pointing_angle_error-val is deprecated.  Use control_msgs-msg:pointing_angle_error instead.")
  (pointing_angle_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointHeadFeedback>) ostream)
  "Serializes a message object of type '<PointHeadFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'pointing_angle_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointHeadFeedback>) istream)
  "Deserializes a message object of type '<PointHeadFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pointing_angle_error) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointHeadFeedback>)))
  "Returns string type for a message object of type '<PointHeadFeedback>"
  "control_msgs/PointHeadFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointHeadFeedback)))
  "Returns string type for a message object of type 'PointHeadFeedback"
  "control_msgs/PointHeadFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointHeadFeedback>)))
  "Returns md5sum for a message object of type '<PointHeadFeedback>"
  "cce80d27fd763682da8805a73316cab4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointHeadFeedback)))
  "Returns md5sum for a message object of type 'PointHeadFeedback"
  "cce80d27fd763682da8805a73316cab4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointHeadFeedback>)))
  "Returns full string definition for message of type '<PointHeadFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 pointing_angle_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointHeadFeedback)))
  "Returns full string definition for message of type 'PointHeadFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 pointing_angle_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointHeadFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointHeadFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PointHeadFeedback
    (cl:cons ':pointing_angle_error (pointing_angle_error msg))
))
