(cl:in-package rosgraph_msgs-msg)
(cl:export '(TOPIC-VAL
          TOPIC
          NODE_PUB-VAL
          NODE_PUB
          NODE_SUB-VAL
          NODE_SUB
          WINDOW_START-VAL
          WINDOW_START
          WINDOW_STOP-VAL
          WINDOW_STOP
          DELIVERED_MSGS-VAL
          DELIVERED_MSGS
          DROPPED_MSGS-VAL
          DROPPED_MSGS
          TRAFFIC-VAL
          TRAFFIC
          PERIOD_MEAN-VAL
          PERIOD_MEAN
          PERIOD_STDDEV-VAL
          PERIOD_STDDEV
          PERIOD_MAX-VAL
          PERIOD_MAX
          STAMP_AGE_MEAN-VAL
          STAMP_AGE_MEAN
          STAMP_AGE_STDDEV-VAL
          STAMP_AGE_STDDEV
          STAMP_AGE_MAX-VAL
          STAMP_AGE_MAX
))