; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude AveragingGoal.msg.html

(cl:defclass <AveragingGoal> (roslisp-msg-protocol:ros-message)
  ((samples
    :reader samples
    :initarg :samples
    :type cl:integer
    :initform 0))
)

(cl:defclass AveragingGoal (<AveragingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AveragingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AveragingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<AveragingGoal> is deprecated: use actionlib_tutorials-msg:AveragingGoal instead.")))

(cl:ensure-generic-function 'samples-val :lambda-list '(m))
(cl:defmethod samples-val ((m <AveragingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:samples-val is deprecated.  Use actionlib_tutorials-msg:samples instead.")
  (samples m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AveragingGoal>) ostream)
  "Serializes a message object of type '<AveragingGoal>"
  (cl:let* ((signed (cl:slot-value msg 'samples)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AveragingGoal>) istream)
  "Deserializes a message object of type '<AveragingGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'samples) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AveragingGoal>)))
  "Returns string type for a message object of type '<AveragingGoal>"
  "actionlib_tutorials/AveragingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AveragingGoal)))
  "Returns string type for a message object of type 'AveragingGoal"
  "actionlib_tutorials/AveragingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AveragingGoal>)))
  "Returns md5sum for a message object of type '<AveragingGoal>"
  "32c9b10ef9b253faa93b93f564762c8f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AveragingGoal)))
  "Returns md5sum for a message object of type 'AveragingGoal"
  "32c9b10ef9b253faa93b93f564762c8f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AveragingGoal>)))
  "Returns full string definition for message of type '<AveragingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 samples~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AveragingGoal)))
  "Returns full string definition for message of type 'AveragingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 samples~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AveragingGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AveragingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AveragingGoal
    (cl:cons ':samples (samples msg))
))
